import Head from 'next/head'
import Image from 'next/image'
import Countdown from 'react-countdown'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ragnarök Beers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Ragnarök
          </h1>
          <Image
            src="/ragna.png" 
            alt="Ragnarok Beers"
            className={styles.imgShadow}
            width={500}
            height={500}
          />
          <p className={styles.description}>
            Is a place where you can find the best beers in the world. 
            <br></br>
            <Countdown
              className={styles.description}
              date={Date.now() + 1000000} 
            />
          </p>
          <div className={styles.grid}>
          <audio src="/sounds/ragna.mp3" autoPlay></audio>
          </div>
          {/* <Button>
            Let&apos;s go!
          </Button> */}
        </main>
      </div>
      <Footer/>
    </>
  )
}
