import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Countdown from 'react-countdown'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [countdown, _] = useState(()=>{
    const date = new Date()
    date.setHours(23,59,0,0)
    date.setDate(date.getDate())
    console.log(date)
    console.log(Date())
    return date.getTime() - Date.now()
    
  })
  return (
    <>
      <Head>
        <title>Ragnarök Beers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Ragnarök
          </h1>
          <Image
            src="/ragna.png" 
            alt="Ragnarok Beers"
            className={styles.imgShadow}
            width={450}
            height={450}
          />
          <p className={styles.description}>
            Is a place where you can find the best beers in the world. 
            <br></br>
            <Countdown
              className={styles.title}
              date={Date.now() + countdown} 
            />
          </p>
          <div className={styles.grid}>
          </div>
          {/* <Button>
            Let&apos;s go!
          </Button> */}
        </main>
      </div>
      <Footer/>
    </>
  )
}
