import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/footer'
import { Header } from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ragnarök Beers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Ragnarök Beers
          </h1>
          <Image
            src="/ragna.png" 
            alt="Ragnarok Beers"
            width={200}
            height={200}
          />
          <p className={styles.description}>
            Is a place where you can find the best beers in the world.
          </p>
          <div className={styles.grid}>
          </div>
        </main>
      </div>
      <Footer/>
    </>
  )
}
